/* Generated By:JavaCC: Do not edit this line. CompiladorTreeConstants.java Version 7.0.12 */
package br.com.duck.compilador.parser;

public interface CompiladorTreeConstants
{
  public int JJTSEMICOLON = 0;
  public int JJTIDENTIFIER = 1;
  public int JJTASSIGN = 2;
  public int JJTCOMMA = 3;
  public int JJTOPENPAREN = 4;
  public int JJTCLOSEPAREN = 5;
  public int JJTOPENCURLY = 6;
  public int JJTCLOSECURLY = 7;
  public int JJTIFT = 8;
  public int JJTELSET = 9;
  public int JJTELSEIFT = 10;
  public int JJTWHILE = 11;
  public int JJTFOR = 12;
  public int JJTINT = 13;
  public int JJTFLOAT = 14;
  public int JJTSTRING = 15;
  public int JJTOR = 16;
  public int JJTAND = 17;
  public int JJTEQUALS = 18;
  public int JJTLESSTHAN = 19;
  public int JJTGREATERTHAN = 20;
  public int JJTPLUS = 21;
  public int JJTMINUS = 22;
  public int JJTTIMES = 23;
  public int JJTDIVIDED = 24;
  public int JJTNUMBER = 25;
  public int JJTSTART = 26;
  public int JJTSTATEMENT = 27;
  public int JJTVARIABLEDECLARATION = 28;
  public int JJTVARIABLEDECLARATIONS = 29;
  public int JJTMULTIVARIABLEASSIGNMENT = 30;
  public int JJTASSIGNMENT = 31;
  public int JJTCONDITIONAL = 32;
  public int JJTELSE = 33;
  public int JJTELSEIF = 34;
  public int JJTLOOP = 35;
  public int JJTTYPE = 36;
  public int JJTEXPRESSION = 37;
  public int JJTOREXPRESSION = 38;
  public int JJTANDEXPRESSION = 39;
  public int JJTEQUALITYEXPRESSION = 40;
  public int JJTRELATIONALEXPRESSION = 41;
  public int JJTADDITIVEEXPRESSION = 42;
  public int JJTTERM = 43;
  public int JJTFACTOR = 44;


  public String[] jjtNodeName = {
    "Semicolon",
    "Identifier",
    "Assign",
    "Comma",
    "OpenParen",
    "CloseParen",
    "OpenCurly",
    "CloseCurly",
    "IfT",
    "ElseT",
    "ElseIfT",
    "While",
    "For",
    "Int",
    "Float",
    "String",
    "Or",
    "And",
    "Equals",
    "LessThan",
    "GreaterThan",
    "Plus",
    "Minus",
    "Times",
    "Divided",
    "Number",
    "Start",
    "Statement",
    "VariableDeclaration",
    "VariableDeclarations",
    "MultiVariableAssignment",
    "Assignment",
    "Conditional",
    "Else",
    "ElseIf",
    "Loop",
    "Type",
    "Expression",
    "OrExpression",
    "AndExpression",
    "EqualityExpression",
    "RelationalExpression",
    "AdditiveExpression",
    "Term",
    "Factor",
  };
}
/* JavaCC - OriginalChecksum=916fdc171b7403b1a83c0b0a8e2352d1 (do not edit this line) */
