/* Generated By:JJTree&JavaCC: Do not edit this line. CompiladorConstants.java */
package br.com.duck.compilador.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompiladorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int ELSEIF = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int NUM = 14;
  /** RegularExpression Id. */
  int ASSIGN = 15;
  /** RegularExpression Id. */
  int SEMICOLON = 16;
  /** RegularExpression Id. */
  int OPEN_CURLY = 17;
  /** RegularExpression Id. */
  int CLOSE_CURLY = 18;
  /** RegularExpression Id. */
  int OPEN_PAREN = 19;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int EQUALS = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int LESS_THAN = 25;
  /** RegularExpression Id. */
  int GREATER_THAN = 26;
  /** RegularExpression Id. */
  int PLUS = 27;
  /** RegularExpression Id. */
  int MINUST = 28;
  /** RegularExpression Id. */
  int TIMES = 29;
  /** RegularExpression Id. */
  int DIVIDED = 30;
  /** RegularExpression Id. */
  int EOF_TOKEN = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"sepato\"",
    "\"senaopato\"",
    "\"outropato\"",
    "\"repeteopato\"",
    "\"paraopato\"",
    "\"patointeiro\"",
    "\"patoreal\"",
    "\"patoescrito\"",
    "<ID>",
    "<NUM>",
    "\"=\"",
    "\";\"",
    "\"fazisso{\"",
    "\"}\"",
    "\"forassim(\"",
    "\")entao\"",
    "\",\"",
    "\"=ingual=\"",
    "\"&tambem&\"",
    "\"|ouisso|\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"$php$\"",
  };

}
